### PR TITLE
Feature development

### PR DESCRIPTION
**Pull request by mgunduz1**
Project Completed. Built with Ruby. Microverse Ruby Module Project 1 named "Advanced Building Blocks - Bubble Sort".

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @mgunduz1 and @RyelBanfield :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [ ] Your bubble_sort method was unable to sort an array of numbers in increasing order.
* [ ] Your bubble_sort_by method should be able to sort an array by accepting a block

### Make the required changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by RyelBanfield** [comment]
I think @ElijahTobs has gotten something wrong with his review. Can we have another TSE check this? Or can @ElijahTobs provide more details on what exactly is wrong?

**Comment by RyelBanfield** [comment]
Here is a screenshot of the working code.

Screenshot_1

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 
### Hey there :wave: 
##### You have a failing linter and that is because of the redundant return statement you are using. Ruby has implicit return and so you don't have to specify a return when you want the last thing in your code to be returned. Please update accordingly.
slack(@ebeagusamuel)

**Comment by RyelBanfield** [comment]
Thank you for that clear and informative review. Wish more were like that. @ebeagusamuel

**Review by MarilenaRoque — APPROVED** [review]
## Hello Team! :rocket:

Good job! Since you have applied all the required changes I will approve your project.

# Congrats! Your project is approved! 💯 🥇

However, there are observations that you should keep in mind for the next project.

- Follow the right flow established by git-flow. PR should be open from **feature branch** to **development**.
- README.md should have clear instructions about how to run your project locally( Please add instructions to this project before merging it). 

Happy Coding Team! :computer:

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

**Pull request merged**
